### ISSUE TITLE
Rerun existing production data providers in stage to prod using updated configs

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss-deprecated/dlme-metadata#16]
* [x] Penn Museum
* [x] American Numismatic Society
* [x] Met
* [x] University of Pennsylvania Libraries
* [x] Harvard University Library
* [x] Stanford Libraries

**Comment by anarchivist** [comment]
Awaiting full deletion of records from stage and prod

**Comment by jacobthill** [comment]
blocked by https://github.com/sul-dlss/dlme/issues/516
